name: Post message

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Publish
        run: |
          yarn global add @wireapp/changelog-bot
