name: Post message

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Publish
        run: |
          yarn global add @wireapp/changelog-bot
          wire-changelog-bot -e ${{secrets.WIRE_WEBAPP_BOT_EMAIL}} -p ${{secrets.WIRE_WEBAPP_BOT_PASSWORD}} -c ${{secrets.WIRE_WEBAPP_BOT_CONVERSATION}} -m "Hello, world."
