name: Post message

on: push

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Wire GitHub action bot
        uses: wireapp/wire-github-action-bot@master
        with:
          email: ${{secrets.WIRE_BOT_EMAIL}}
          password: ${{secrets.WIRE_BOT_PASSWORD}}
          conversation: '6936f0a3-be49-4f81-b4a7-d734661beff2'
          text: 'Hello, from WebApp!'
